apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: app1
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: java-app
        image: anujatsamuel/devops:replaceImageTag
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 8080
