apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: app1
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
